export const config = {
  emailjs: {
    serviceId:  process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID  ?? 'service_XXXXXXX',
    templateId: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID ?? 'template_XXXXXXX',
    publicKey:  process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY  ?? 'XXXXXXXXXXXXXXX',
  },
  contact: {
    whatsapp:  process.env.NEXT_PUBLIC_WHATSAPP_NUMBER   ?? '14076331948',
    email:     process.env.NEXT_PUBLIC_CONTACT_EMAIL     ?? 'karla@karlota.net',
    instagram: process.env.NEXT_PUBLIC_INSTAGRAM_HANDLE  ?? '@karlotagourmet',
  },
}

export const DISHES = [
  'Salmon Gravlax',
  'Salgados',
  'Charcuterie Board',
  'Burrata Caprese',
  'Brie',
  'Paella',
  'Filet Mignon',
  'White Rice',
  'Ravioli',
  'Shrimp',
]

export const DISHES_PT = [
  'Salmão Gravlax',
  'Salgados',
  'Tábua de Frios',
  'Burrata Caprese',
  'Brie',
  'Paella',
  'Filé Mignon',
  'Arroz Branco',
  'Ravióli',
  'Camarão',
]

export const PACKAGES = [
  {
    id: 'essencial',
    name: 'Essencial',
    namePt: 'Essencial',
    price: 89,
    tagline: 'The perfect start for intimate gatherings',
    taglinePt: 'O começo perfeito para encontros íntimos',
    inclusions: [
      '4-hour service window',
      'Signature Cocktail hour / Gourmet table',
      'Choice of 2 main dishes',
      '2 sides + salad',
      'Professional serving staff',
      'Setup & cleanup included',
    ],
    inclusionsPt: [
      'Janela de serviço de 4 horas',
      'Hora do coquetel / mesa gourmet',
      'Escolha de 2 pratos principais',
      '2 acompanhamentos + salada',
      'Equipe de serviço profissional',
      'Montagem e desmontagem incluídas',
    ],
  },
  {
    id: 'classico',
    name: 'Classic',
    namePt: 'Clássico',
    price: 109,
    tagline: 'Our most celebrated offering',
    taglinePt: 'Nossa oferta mais celebrada',
    popular: true,
    inclusions: [
      '4-hour service window',
      'Dedicated event coordinator',
      'Signature Cocktail hour / Gourmet table',
      'Choice of 3 main dishes',
      '3 sides + salad',
      'Florals & table styling',
      'Professional serving staff',
      'Setup & breakdown included',
    ],
    inclusionsPt: [
      'Janela de serviço de 4 horas',
      'Coordenador de eventos dedicado',
      'Hora do coquetel / mesa gourmet',
      'Escolha de 3 pratos principais',
      '3 acompanhamentos + salada',
      'Florais e decoração de mesa',
      'Equipe de serviço profissional',
      'Montagem e desmontagem incluídas',
    ],
  },
  {
    id: 'grand-luxe',
    name: 'Grand Luxe',
    namePt: 'Grand Luxe',
    price: 129,
    tagline: 'An unforgettable culinary experience',
    taglinePt: 'Uma experiência culinária inesquecível',
    inclusions: [
      'Full-day service',
      'Signature Cocktail hour / Gourmet table',
      "Chef's choice 5-course tasting menu",
      'Live cooking station',
      'Custom menu curation with chef',
      'Premium florals & décor',
      'Priority weekend booking',
    ],
    inclusionsPt: [
      'Serviço de dia completo',
      'Hora do coquetel / mesa gourmet',
      'Menu degustação de 5 etapas à escolha do chef',
      'Estação de culinária ao vivo',
      'Menu personalizado com o chef',
      'Florais e decoração premium',
      'Reserva prioritária nos finais de semana',
    ],
  },
]
